// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ESTSCarro_JL.Migrations
{
    [DbContext(typeof(ESTSCarro_JLContext))]
    [Migration("20251216153720_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ESTSCarro_JL.Models.Carro_JL", b =>
                {
                    b.Property<Guid>("Carro_JLId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Marca_JL")
                        .HasColumnType("int");

                    b.Property<int>("Modelo_JL")
                        .HasColumnType("int");

                    b.HasKey("Carro_JLId");

                    b.ToTable("Carro_JL");
                });
#pragma warning restore 612, 618
        }
    }
}
